In [1]:
# 逻辑回归
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model as lm
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
# 导入数据

df = pd.read_csv("iris.csv")

df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [2]:
# 设置自变量X和因变量Y
X = df.iloc[:,:4]
y = df['species']

In [3]:
# 逻辑回归
LogReg = lm.LogisticRegression() # 构建模型对象
LogReg.fit(X,y)   # 传入数据，计算模型
print('拟合得分：',LogReg.score(X,y))  # 拟合得分
print('系数估计：\n',LogReg.coef_)  # 参数估计
print('截距估计：',LogReg.intercept_)  # 参数估计
df['LogReg'] = LogReg.predict(X) # 保存预测结果
x = [[4.8,3.2,1.6,0.5]]
print('样本预测：',x,'--->',LogReg.predict(x))  # 预测测试数据

print('\n预测结果统计（列联表）：\n',pd.crosstab(df['species'],df['LogReg']))

拟合得分： 0.9733333333333334
系数估计：
 [[-0.41816109  0.96642034 -2.52142982 -1.08402417]
 [ 0.53103942 -0.31447466 -0.19925703 -0.94918921]
 [-0.11287832 -0.65194568  2.72068685  2.03321338]]
截距估计： [  9.83922547   2.21463083 -12.0538563 ]
样本预测： [[4.8, 3.2, 1.6, 0.5]] ---> ['setosa']

预测结果统计（列联表）：
 LogReg      setosa  versicolor  virginica
species                                  
setosa          50           0          0
versicolor       0          47          3
virginica        0           1         49


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [4]:
# 朴素贝叶斯分类
from sklearn.naive_bayes import GaussianNB

Gnb = GaussianNB() # 构建模型对象
Gnb.fit(X,y)   # 传入数据，计算模型
print('拟合得分：',Gnb.score(X,y))  # 拟合得分
df['Gnb'] = Gnb.predict(X) # 保存预测结果
x = [[4.8,3.2,1.6,0.5]]
print('样本预测：',x,'--->',Gnb.predict(x))  # 预测测试数据
print('\n预测结果统计（列联表）：\n',pd.crosstab(df['species'],df['Gnb']))

拟合得分： 0.96
样本预测： [[4.8, 3.2, 1.6, 0.5]] ---> ['setosa']

预测结果统计（列联表）：
 Gnb         setosa  versicolor  virginica
species                                  
setosa          50           0          0
versicolor       0          47          3
virginica        0           3         47


In [5]:
# 决策树
from sklearn import tree
dTree = tree.DecisionTreeClassifier()  # 决策树分类器对象
dTree.fit(X,y)  # 传入数据，计算模型
print('拟合得分：',dTree.score(X,y))  # 拟合得分
df['dTree'] = dTree.predict(X) # 保存预测结果
x = [[4.8,3.2,1.6,0.5]]
print('样本预测：',x,'--->',dTree.predict(x))  # 预测测试数据
print('\n预测结果统计（列联表）：\n',pd.crosstab(df['species'],df['dTree']))

拟合得分： 1.0
样本预测： [[4.8, 3.2, 1.6, 0.5]] ---> ['setosa']

预测结果统计（列联表）：
 dTree       setosa  versicolor  virginica
species                                  
setosa          50           0          0
versicolor       0          50          0
virginica        0           0         50


In [6]:
# 随机深林
from sklearn.ensemble import RandomForestClassifier
rndForest = RandomForestClassifier()  # 随机森林分类器对象
rndForest.fit(X,y)  # 传入数据，计算模型

print('拟合得分：',rndForest.score(X,y))  # 拟合得分
df['rndForest'] = rndForest.predict(X) # 保存预测结果
x = [[4.8,3.2,1.6,0.5]]
print('样本预测：',x,'--->',rndForest.predict(x))  # 预测测试数据
print('\n预测结果统计（列联表）：\n',pd.crosstab(df['species'],df['rndForest']))

拟合得分： 1.0
样本预测： [[4.8, 3.2, 1.6, 0.5]] ---> ['setosa']

预测结果统计（列联表）：
 rndForest   setosa  versicolor  virginica
species                                  
setosa          50           0          0
versicolor       0          50          0
virginica        0           0         50


In [7]:
# 支持向量机
from sklearn import svm
svc = svm.SVC()  # 创建分类器对象
svc.fit(X,y)
print('拟合得分：',svc.score(X,y))  # 拟合得分
df['svc'] = svc.predict(X) # 保存预测结果
x = [[4.8,3.2,1.6,0.5]]
print('样本预测：',x,'--->',svc.predict(x))  # 预测测试数据
print('\n预测结果统计（列联表）：\n',pd.crosstab(df['species'],df['svc']))

拟合得分： 0.9733333333333334
样本预测： [[4.8, 3.2, 1.6, 0.5]] ---> ['setosa']

预测结果统计（列联表）：
 svc         setosa  versicolor  virginica
species                                  
setosa          50           0          0
versicolor       0          48          2
virginica        0           2         48


In [8]:
# KNN算法——K近邻
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X,y)

print('拟合得分：',knn.score(X,y))  # 拟合得分
df['knn'] = knn.predict(X) # 保存预测结果
x = [[4.8,3.2,1.6,0.5]]
print('样本预测：',x,'--->',knn.predict(x))  # 预测测试数据
print('\n预测结果统计（列联表）：\n',pd.crosstab(df['species'],df['knn']))

拟合得分： 0.9666666666666667
样本预测： [[4.8, 3.2, 1.6, 0.5]] ---> ['setosa']

预测结果统计（列联表）：
 knn         setosa  versicolor  virginica
species                                  
setosa          50           0          0
versicolor       0          47          3
virginica        0           2         48


In [9]:
df

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

        LogReg        Gnb      dTree  rndForest        svc        knn  
0       setosa     setosa     setosa     setosa     setosa     setosa  
1       setosa     setosa     setosa     setosa     setosa     setosa  
2       setosa     setosa     setosa     setosa     setosa     setosa  
3       setosa     setosa     setosa     setosa     setosa     setosa  
4       setosa     setosa     setosa     setosa     setosa     setosa  
..         ...        ...        ...        ...        ...        ...  
145  virginica  virginica  virginica  virginica  virginica  virginica  
146  virginica  virginica  virginica  virginica  virginica  virginica  
147  virginica  virginica  virginica  virginica  virginica  virginica  
148  virginica  virginica  virginica  virginica  virginica  virginica  
149  virginica  virginica  virginica  virginica  virginica  virginica  

[150 rows x 11 columns]